steps:
    - name: node
      entrypoint: npm
      args: ['install']

    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['-m', 'rm', 'gs://app.assetalchemy.io/**']

    - name: 'gcr.io/cloud-builders/gsutil'
      dir: 'build'
      args: ['-m', 'cp', '-r', '.', 'gs://app.assetalchemy.io/']
