export const metrics: any = {
    changePercent: { label: 'Change %', type: 'number' },
    latestPrice: { label: 'Latest Price', type: 'number' },
    blockTraded: { label: 'Block Traded on IEX', type: 'event' },
    hasDividendNextDay: { label: 'Dividend Next Day Ex', type: 'event' },
    hasDividendToday: { label: 'Dividend Today', type: 'event' },
    hasClosingPrice: { label: 'Has a closing price', type: 'event' },
    hasOpeningPrice: { label: 'Has an opening price', type: 'event' },
    hasIEXMinuteBar: { label: 'Has IEX Minute Bar', type: 'event' },
    hasMinuteBar: { label: 'Has Minute Bar', type: 'event' },
    hasNews: { label: 'Has News', type: 'event' },
    avgTotalVolume: { label: 'Avg Volume', type: 'number' },
    change: { label: 'Change Amount', type: 'number' },
    ttmDividendRate: { label: 'Dividend Rate', type: 'number' },
    dividendYield: { label: 'Dividend Yield', type: 'number' },
    high: { label: 'High', type: 'number' },
    low: { label: 'Low', type: 'number' },
    marketCap: { label: 'Market Cap', type: 'number' },
    peRatio: { label: 'PE Ratio', type: 'number' },
    MarketPeerPriceChangePercent: {
        label: 'Peer Price Change %',
        type: 'number',
    },
    MarketPriceChangePercentVsPeers: {
        label: 'Price Change % vs Peers',
        type: 'number',
    },
    MarketPriceChangePercentVsSector: {
        label: 'Price Change % vs Sector',
        type: 'number',
    },
    sector: { label: 'Sector', type: 'string' },
    ytdChange: { label: 'YTD Change %', type: 'number' },
    avg10Volume: { label: '10 Day Average Volume', type: 'number' },
    year2ChangePercent: { label: '2 Year Change %', type: 'number' },
    day200MovingAvg: {
        label: '200 Day Moving Average',
        type: 'number',
    },
    avg30Volume: { label: '30 Day Average Volume', type: 'number' },
    day30ChangePercent: { label: '30 Day Change %', type: 'number' },
    day5ChangePercent: { label: '5 Day Change %', type: 'number' },
    year5ChangePercent: { label: '5 Year Change %', type: 'number' },
    day50MovingAvg: { label: '50 Day Moving Average', type: 'number' },
    week52change: { label: '52 Week Change %', type: 'number' },
    week52high: { label: '52 Week High', type: 'number' },
    week52low: { label: '52 Week Low', type: 'number' },
    beta: { label: 'Beta', type: 'number' },
    currentDebt: { label: 'Current Debt', type: 'number' },
    debtToEquity: { label: 'Debt to Equity', type: 'number' },
    EBITDA: { label: 'EBITDA', type: 'number' },
    enterpriseValue: { label: 'Enterprise Value', type: 'number' },
    enterpriseValueToRevenue: {
        label: 'Enterprise Value to Revenue',
        type: 'number',
    },
    forwardPERatio: { label: 'Forward PE', type: 'number' },
    nextDividendDate: { label: 'Next Dividend', type: 'date' },
    nextEarningsDate: { label: 'Next Earnings', type: 'date' },
    pegRatio: { label: 'PEG Ratio', type: 'number' },
    priceToBook: { label: 'Price to Book', type: 'number' },
    priceToSales: { label: 'Price to Sales', type: 'number' },
    profitMargin: { label: 'Profit Margin', type: 'number' },
    revenue: { label: 'Revenue', type: 'number' },
    revenuePerEmployee: {
        label: 'Revenue per employee',
        type: 'number',
    },
    revenuePerShare: { label: 'Revenue per share', type: 'number' },
    symbolChangeVsSectorChange: {
        label: 'Stock vs Sector Change %',
        type: 'number',
    },
    totalCash: { label: 'Total Cash', type: 'number' },
    totalRevenue: { label: 'Total Revenue', type: 'number' },
    Day30PeerAverageVolume: {
        label: '30 Day Peer Average Volume',
        type: 'number',
    },
    Day30PeerAverageVolumeStandardDeviationX2: {
        label: '30 Day Peer Average Volume 2x Standard Deviation',
        type: 'number',
    },
    Day30PeerAverageVolumeStandardDeviation: {
        label: '30 Day Peer Average Volume Standard Deviation',
        type: 'number',
    },
    extendedChangePercent: {
        label: 'Extended Hours Change %',
        type: 'number',
    },
    Day30PeerAveragePrice: {
        label: '30 Day Peer Average Price',
        type: 'number',
    },
    Day30PeerAveragePriceStandardDeviation: {
        label: '30 Day Peer Average Price Standard Deviation',
        type: 'number',
    },
    sharesOutstanding: { label: 'Shares Outstanding', type: 'number' },
    DGS1MO: { label: '1-Month Treasury', type: 'number' },
    DGS1: { label: '1-Year Treasury', type: 'number' },
    DGS10: { label: '10-Year Treasury', type: 'number' },
    MORTGAGE15US: { label: '15-Year Mortgage Rate', type: 'number' },
    DGS2: { label: '2-Year Treasury', type: 'number' },
    DGS20: { label: '20-Year Treasury', type: 'number' },
    DGS3MO: { label: '3-Month Treasury', type: 'number' },
    MORTGAGE30US: { label: '30-Year Mortgage Rate', type: 'number' },
    DGS30: { label: '30-Year Treasury', type: 'number' },
    MORTGAGE5US: { label: '5-Year Mortgage Rate', type: 'number' },
    DGS5: { label: '5-Year Treasury', type: 'number' },
    DGS6MO: { label: '6-Month Treasury', type: 'number' },
    DCOILBRENTEU: { label: 'Crude Brent Oil Price', type: 'number' },
    DCOILWTICO: { label: 'Crude Oil Price', type: 'number' },
    SectorChangePercent: { label: 'Sector Change %', type: 'number' },
    UNRATE: { label: 'Unemployment Rate', type: 'number' },
    Day30PeerAveragePriceStandardDeviationX2: {
        label: '30 Day Peer Average Price 2x Standard Deviation',
        type: 'number',
    },
    Day30AveragePrice: {
        label: '30 Day Average Price',
        type: 'number',
    },
    Day30AveragePriceStandardDeviationX2: {
        label: '30 Day Average Price 2x Standard Deviation',
        type: 'number',
    },
    Day30AveragePriceStandardDeviation: {
        label: '30 Day Average Price Standard Deviation',
        type: 'number',
    },
    Day30AverageVolume: {
        label: '30 Day Average Volume',
        type: 'number',
    },
    Day30AverageVolumeStandardDeviationX2: {
        label: '30 Day Average Volume 2x Standard Deviation',
        type: 'number',
    },
    Day30AverageVolumeStandardDeviation: {
        label: '30 Day Average Volume Standard Deviation',
        type: 'number',
    },
    ceo_salary: { label: 'CEO Salary', type: 'number' },
    employees: { label: 'Employees', type: 'number' },
    exchange: { label: 'Exchange', type: 'string' },
    extendedPrice: { label: 'Extended Price', type: 'number' },
    float: { label: 'Float', type: 'number' },
    isUSMarketOpen: { label: 'Is Market Hours', type: 'boolean' },
}

export const reverseMetrics: any = {
    'Change %': 'changePercent',
    'Latest Price': 'latestPrice',
    'Block Traded on IEX': 'blockTraded',
    'Dividend Next Day Ex': 'hasDividendNextDay',
    'Dividend Today': 'hasDividendToday',
    'Has a closing price': 'hasClosingPrice',
    'Has an opening price': 'hasOpeningPrice',
    'Has IEX Minute Bar': 'hasIEXMinuteBar',
    'Has Minute Bar': 'hasMinuteBar',
    'Has News': 'hasNews',
    'Avg Volume': 'avgTotalVolume',
    'Change Amount': 'change',
    'Dividend Rate': 'ttmDividendRate',
    'Dividend Yield': 'dividendYield',
    High: 'high',
    Low: 'low',
    'Market Cap': 'marketCap',
    'PE Ratio': 'peRatio',
    'Peer Price Change %': 'MarketPeerPriceChangePercent',
    'Price Change % vs Peers': 'MarketPriceChangePercentVsPeers',
    'Price Change % vs Sector': 'MarketPriceChangePercentVsSector',
    Sector: 'sector',
    'YTD Change %': 'ytdChange',
    '10 Day Average Volume': 'avg10Volume',
    '2 Year Change %': 'year2ChangePercent',
    '200 Day Moving Average': 'day200MovingAvg',
    '30 Day Average Volume': 'Day30AverageVolume',
    '30 Day Change %': 'day30ChangePercent',
    '5 Day Change %': 'day5ChangePercent',
    '5 Year Change %': 'year5ChangePercent',
    '50 Day Moving Average': 'day50MovingAvg',
    '52 Week Change %': 'week52change',
    '52 Week High': 'week52high',
    '52 Week Low': 'week52low',
    Beta: 'beta',
    'Current Debt': 'currentDebt',
    'Debt to Equity': 'debtToEquity',
    EBITDA: 'EBITDA',
    'Enterprise Value': 'enterpriseValue',
    'Enterprise Value to Revenue': 'enterpriseValueToRevenue',
    'Forward PE': 'forwardPERatio',
    'PEG Ratio': 'pegRatio',
    'Price to Book': 'priceToBook',
    'Price to Sales': 'priceToSales',
    'Profit Margin': 'profitMargin',
    Revenue: 'revenue',
    'Revenue per employee': 'revenuePerEmployee',
    'Revenue per share': 'revenuePerShare',
    'Stock vs Sector Change %': 'symbolChangeVsSectorChange',
    'Total Cash': 'totalCash',
    'Total Revenue': 'totalRevenue',
    '30 Day Peer Average Volume': 'Day30PeerAverageVolume',
    '30 Day Peer Average Volume 2x Standard Deviation':
        'Day30PeerAverageVolumeStandardDeviationX2',
    '30 Day Peer Average Volume Standard Deviation':
        'Day30PeerAverageVolumeStandardDeviation',
    'Extended Hours Change %': 'extendedChangePercent',
    '30 Day Peer Average Price': 'Day30PeerAveragePrice',
    '30 Day Peer Average Price Standard Deviation':
        'Day30PeerAveragePriceStandardDeviation',
    'Shares Outstanding': 'sharesOutstanding',
    '1-Month Treasury': 'DGS1MO',
    '1-Year Treasury': 'DGS1',
    '10-Year Treasury': 'DGS10',
    '15-Year Mortgage Rate': 'MORTGAGE15US',
    '2-Year Treasury': 'DGS2',
    '20-Year Treasury': 'DGS20',
    '3-Month Treasury': 'DGS3MO',
    '30-Year Mortgage Rate': 'MORTGAGE30US',
    '30-Year Treasury': 'DGS30',
    '5-Year Mortgage Rate': 'MORTGAGE5US',
    '5-Year Treasury': 'DGS5',
    '6-Month Treasury': 'DGS6MO',
    'Crude Brent Oil Price': 'DCOILBRENTEU',
    'Crude Oil Price': 'DCOILWTICO',
    'Sector Change %': 'SectorChangePercent',
    'Unemployment Rate': 'UNRATE',
    '30 Day Peer Average Price 2x Standard Deviation':
        'Day30PeerAveragePriceStandardDeviationX2',
    '30 Day Average Price': 'Day30AveragePrice',
    '30 Day Average Price 2x Standard Deviation':
        'Day30AveragePriceStandardDeviationX2',
    '30 Day Average Price Standard Deviation':
        'Day30AveragePriceStandardDeviation',
    '30 Day Average Volume 2x Standard Deviation':
        'Day30AverageVolumeStandardDeviationX2',
    '30 Day Average Volume Standard Deviation':
        'Day30AverageVolumeStandardDeviation',
    'CEO Salary': 'ceo_salary',
    Employees: 'employees',
    Exchange: 'exchange',
    'Extended Price': 'extendedPrice',
    Float: 'float',
    'Is Market Hours': 'isUSMarketOpen',
}

export const conditionsList: any = {
    metrics: [
        'Change %',
        'Latest Price',
        'Dividend Next Day Ex',
        'Dividend Today',
        'Has News',
        'Avg Volume',
        'Change Amount',
        'Dividend Rate',
        'Dividend Yield',
        'High',
        'Low',
        'Market Cap',
        'PE Ratio',
        'Peer Price Change %',
        'Price Change % vs Peers',
        'Price Change % vs Sector',
        'Sector',
        'YTD Change %',
        '10 Day Average Volume',
        '2 Year Change %',
        '200 Day Moving Average',
        '30 Day Average Volume',
        '30 Day Change %',
        '5 Day Change %',
        '5 Year Change %',
        '50 Day Moving Average',
        '52 Week Change %',
        '52 Week High',
        '52 Week Low',
        'Beta',
        'Current Debt',
        'Debt to Equity',
        'EBITDA',
        'Enterprise Value',
        'Enterprise Value to Revenue',
        'Forward PE',
        'PEG Ratio',
        'Price to Book',
        'Price to Sales',
        'Profit Margin',
        'Revenue',
        'Revenue per employee',
        'Revenue per share',
        'Stock vs Sector Change %',
        'Total Cash',
        'Total Revenue',
        '30 Day Peer Average Volume',
        '30 Day Peer Average Volume 2x Standard Deviation',
        '30 Day Peer Average Volume Standard Deviation',
        'Extended Hours Change %',
        '30 Day Peer Average Price',
        '30 Day Peer Average Price Standard Deviation',
        'Shares Outstanding',
        '1-Month Treasury',
        '1-Year Treasury',
        '10-Year Treasury',
        '15-Year Mortgage Rate',
        '2-Year Treasury',
        '20-Year Treasury',
        '3-Month Treasury',
        '30-Year Mortgage Rate',
        '30-Year Treasury',
        '5-Year Mortgage Rate',
        '5-Year Treasury',
        '6-Month Treasury',
        'Crude Brent Oil Price',
        'Crude Oil Price',
        'Sector',
        'Sector Change %',
        'Unemployment Rate',
        '30 Day Peer Average Price 2x Standard Deviation',
        '30 Day Average Price',
        '30 Day Average Price 2x Standard Deviation',
        '30 Day Average Price Standard Deviation',
        '30 Day Average Volume 2x Standard Deviation',
        '30 Day Average Volume Standard Deviation',
        'Extended Price',
        'Float',
        'Is Market Hours',
    ],
    operators: {
        number: [
            'is above',
            'is above or equal to',
            'is below',
            'is below or equal to',
            'is',
            'is not',
        ],
        boolean: ['is'],
        string: ['is'],
        event: ['is'],
    },
    values: {
        boolean: ['True', 'False'],
        event: ['True', 'False'],
    },
}

export const operators: any = {
    '>': 'is above',
    '>=': 'is above or equal to',
    '<': 'is below',
    '<=': 'is below or equal to',
    '==': 'is',
    '!=': 'is not',
    true: 'True',
    false: 'False',
}

export const reverseOperators: any = {
    'is above': '>',
    'is above or equal to': '>=',
    'is below': '<',
    'is below or equal to': '<=',
    is: '==',
    'is not': '!=',
    True: 'true',
    False: 'false',
}
