export const metrics: any = {
    changePercent: { label: 'Symbol: Change %', type: 'number' },
    latestPrice: { label: 'Symbol: Latest Price', type: 'number' },
    blockTraded: { label: 'Event: Block Traded on IEX', type: 'event' },
    hasDividendNextDay: { label: 'Event: Dividend Next Day Ex', type: 'event' },
    hasDividendToday: { label: 'Event: Dividend Today', type: 'event' },
    hasClosingPrice: { label: 'Event: Has a closing price', type: 'event' },
    hasOpeningPrice: { label: 'Event: Has an opening price', type: 'event' },
    hasIEXMinuteBar: { label: 'Event: Has IEX Minute Bar', type: 'event' },
    hasMinuteBar: { label: 'Event: Has Minute Bar', type: 'event' },
    hasNews: { label: 'Event: Has News', type: 'event' },
    avgTotalVolume: { label: 'Symbol: Avg Volume', type: 'number' },
    change: { label: 'Symbol: Change Amount', type: 'number' },
    ttmDividendRate: { label: 'Symbol: Dividend Rate', type: 'number' },
    dividendYield: { label: 'Symbol: Dividend Yield', type: 'number' },
    high: { label: 'Symbol: High', type: 'number' },
    low: { label: 'Symbol: Low', type: 'number' },
    marketCap: { label: 'Symbol: Market Cap', type: 'number' },
    peRatio: { label: 'Symbol: PE Ratio', type: 'number' },
    MarketPeerPriceChangePercent: {
        label: 'Symbol: Peer Price Change %',
        type: 'number',
    },
    MarketPriceChangePercentVsPeers: {
        label: 'Symbol: Price Change % vs Peers',
        type: 'number',
    },
    MarketPriceChangePercentVsSector: {
        label: 'Symbol: Price Change % vs Sector',
        type: 'number',
    },
    sector: { label: 'Global: Sector', type: 'string' },
    ytdChange: { label: 'Symbol: YTD Change %', type: 'number' },
    avg10Volume: { label: 'Symbol: 10 Day Average Volume', type: 'number' },
    year2ChangePercent: { label: 'Symbol: 2 Year Change %', type: 'number' },
    day200MovingAvg: {
        label: 'Symbol: 200 Day Moving Average',
        type: 'number',
    },
    avg30Volume: { label: 'Symbol: 30 Day Average Volume', type: 'number' },
    day30ChangePercent: { label: 'Symbol: 30 Day Change %', type: 'number' },
    day5ChangePercent: { label: 'Symbol: 5 Day Change %', type: 'number' },
    year5ChangePercent: { label: 'Symbol: 5 Year Change %', type: 'number' },
    day50MovingAvg: { label: 'Symbol: 50 Day Moving Average', type: 'number' },
    week52change: { label: 'Symbol: 52 Week Change %', type: 'number' },
    week52high: { label: 'Symbol: 52 Week High', type: 'number' },
    week52low: { label: 'Symbol: 52 Week Low', type: 'number' },
    beta: { label: 'Symbol: Beta', type: 'number' },
    currentDebt: { label: 'Symbol: Current Debt', type: 'number' },
    debtToEquity: { label: 'Symbol: Debt to Equity', type: 'number' },
    EBITDA: { label: 'Symbol: EBITDA', type: 'number' },
    enterpriseValue: { label: 'Symbol: Enterprise Value', type: 'number' },
    enterpriseValueToRevenue: {
        label: 'Symbol: Enterprise Value to Revenue',
        type: 'number',
    },
    forwardPERatio: { label: 'Symbol: Forward PE', type: 'number' },
    nextDividendDate: { label: 'Symbol: Next Dividend', type: 'date' },
    nextEarningsDate: { label: 'Symbol: Next Earnings', type: 'date' },
    pegRatio: { label: 'Symbol: PEG Ratio', type: 'number' },
    priceToBook: { label: 'Symbol: Price to Book', type: 'number' },
    priceToSales: { label: 'Symbol: Price to Sales', type: 'number' },
    profitMargin: { label: 'Symbol: Profit Margin', type: 'number' },
    revenue: { label: 'Symbol: Revenue', type: 'number' },
    revenuePerEmployee: {
        label: 'Symbol: Revenue per employee',
        type: 'number',
    },
    revenuePerShare: { label: 'Symbol: Revenue per share', type: 'number' },
    symbolChangeVsSectorChange: {
        label: 'Symbol: Stock vs Sector Change %',
        type: 'number',
    },
    totalCash: { label: 'Symbol: Total Cash', type: 'number' },
    totalRevenue: { label: 'Symbol: Total Revenue', type: 'number' },
    Day30PeerAverageVolume: {
        label: 'Peers: 30 Day Peer Average Volume',
        type: 'number',
    },
    Day30PeerAverageVolumeStandardDeviationX2: {
        label: 'Peers: 30 Day Peer Average Volume 2x Standard Deviation',
        type: 'number',
    },
    Day30PeerAverageVolumeStandardDeviation: {
        label: 'Peers: 30 Day Peer Average Volume Standard Deviation',
        type: 'number',
    },
    extendedChangePercent: {
        label: 'Symbol: Extended Hours Change %',
        type: 'number',
    },
    Day30PeerAveragePrice: {
        label: 'Peers: 30 Day Peer Average Price',
        type: 'number',
    },
    Day30PeerAveragePriceStandardDeviation: {
        label: 'Peers: 30 Day Peer Average Price Standard Deviation',
        type: 'number',
    },
    sharesOutstanding: { label: 'Symbol: Shares Outstanding', type: 'number' },
    DGS1MO: { label: 'Global: 1-Month Treasury', type: 'number' },
    DGS1: { label: 'Global: 1-Year Treasury', type: 'number' },
    DGS10: { label: 'Global: 10-Year Treasury', type: 'number' },
    MORTGAGE15US: { label: 'Global: 15-Year Mortgage Rate', type: 'number' },
    DGS2: { label: 'Global: 2-Year Treasury', type: 'number' },
    DGS20: { label: 'Global: 20-Year Treasury', type: 'number' },
    DGS3MO: { label: 'Global: 3-Month Treasury', type: 'number' },
    MORTGAGE30US: { label: 'Global: 30-Year Mortgage Rate', type: 'number' },
    DGS30: { label: 'Global: 30-Year Treasury', type: 'number' },
    MORTGAGE5US: { label: 'Global: 5-Year Mortgage Rate', type: 'number' },
    DGS5: { label: 'Global: 5-Year Treasury', type: 'number' },
    DGS6MO: { label: 'Global: 6-Month Treasury', type: 'number' },
    DCOILBRENTEU: { label: 'Global: Crude Brent Oil Price', type: 'number' },
    DCOILWTICO: { label: 'Global: Crude Oil Price', type: 'number' },
    SectorChangePercent: { label: 'Global: Sector Change %', type: 'number' },
    UNRATE: { label: 'Global: Unemployment Rate', type: 'number' },
    Day30PeerAveragePriceStandardDeviationX2: {
        label: 'Peers: 30 Day Peer Average Price 2x Standard Deviation',
        type: 'number',
    },
    Day30AveragePrice: {
        label: 'Symbol: 30 Day Average Price',
        type: 'number',
    },
    Day30AveragePriceStandardDeviationX2: {
        label: 'Symbol: 30 Day Average Price 2x Standard Deviation',
        type: 'number',
    },
    Day30AveragePriceStandardDeviation: {
        label: 'Symbol: 30 Day Average Price Standard Deviation',
        type: 'number',
    },
    Day30AverageVolume: {
        label: 'Symbol: 30 Day Average Volume',
        type: 'number',
    },
    Day30AverageVolumeStandardDeviationX2: {
        label: 'Symbol: 30 Day Average Volume 2x Standard Deviation',
        type: 'number',
    },
    Day30AverageVolumeStandardDeviation: {
        label: 'Symbol: 30 Day Average Volume Standard Deviation',
        type: 'number',
    },
    ceo_salary: { label: 'Symbol: CEO Salary', type: 'number' },
    employees: { label: 'Symbol: Employees', type: 'number' },
    exchange: { label: 'Symbol: Exchange', type: 'string' },
    extendedPrice: { label: 'Symbol: Extended Price', type: 'number' },
    float: { label: 'Symbol: Float', type: 'number' },
    isUSMarketOpen: { label: 'Symbol: Is Market Hours', type: 'boolean' },
}

export const reverseMetrics: any = {
    'Symbol: Change %': 'changePercent',
    'Symbol: Latest Price': 'latestPrice',
    'Event: Block Traded on IEX': 'blockTraded',
    'Event: Dividend Next Day Ex': 'hasDividendNextDay',
    'Event: Dividend Today': 'hasDividendToday',
    'Event: Has a closing price': 'hasClosingPrice',
    'Event: Has an opening price': 'hasOpeningPrice',
    'Event: Has IEX Minute Bar': 'hasIEXMinuteBar',
    'Event: Has Minute Bar': 'hasMinuteBar',
    'Event: Has News': 'hasNews',
    'Symbol: Avg Volume': 'avgTotalVolume',
    'Symbol: Change Amount': 'change',
    'Symbol: Dividend Rate': 'ttmDividendRate',
    'Symbol: Dividend Yield': 'dividendYield',
    'Symbol: High': 'high',
    'Symbol: Low': 'low',
    'Symbol: Market Cap': 'marketCap',
    'Symbol: PE Ratio': 'peRatio',
    'Symbol: Peer Price Change %': 'MarketPeerPriceChangePercent',
    'Symbol: Price Change % vs Peers': 'MarketPriceChangePercentVsPeers',
    'Symbol: Price Change % vs Sector': 'MarketPriceChangePercentVsSector',
    'Symbol: Sector': 'sector',
    'Symbol: YTD Change %': 'ytdChange',
    'Symbol: 10 Day Average Volume': 'avg10Volume',
    'Symbol: 2 Year Change %': 'year2ChangePercent',
    'Symbol: 200 Day Moving Average': 'day200MovingAvg',
    'Symbol: 30 Day Average Volume': 'Day30AverageVolume',
    'Symbol: 30 Day Change %': 'day30ChangePercent',
    'Symbol: 5 Day Change %': 'day5ChangePercent',
    'Symbol: 5 Year Change %': 'year5ChangePercent',
    'Symbol: 50 Day Moving Average': 'day50MovingAvg',
    'Symbol: 52 Week Change %': 'week52change',
    'Symbol: 52 Week High': 'week52high',
    'Symbol: 52 Week Low': 'week52low',
    'Symbol: Beta': 'beta',
    'Symbol: Current Debt': 'currentDebt',
    'Symbol: Debt to Equity': 'debtToEquity',
    'Symbol: EBITDA': 'EBITDA',
    'Symbol: Enterprise Value': 'enterpriseValue',
    'Symbol: Enterprise Value to Revenue': 'enterpriseValueToRevenue',
    'Symbol: Forward PE': 'forwardPERatio',
    'Symbol: PEG Ratio': 'pegRatio',
    'Symbol: Price to Book': 'priceToBook',
    'Symbol: Price to Sales': 'priceToSales',
    'Symbol: Profit Margin': 'profitMargin',
    'Symbol: Revenue': 'revenue',
    'Symbol: Revenue per employee': 'revenuePerEmployee',
    'Symbol: Revenue per share': 'revenuePerShare',
    'Symbol: Stock vs Sector Change %': 'symbolChangeVsSectorChange',
    'Symbol: Total Cash': 'totalCash',
    'Symbol: Total Revenue': 'totalRevenue',
    'Peers: 30 Day Peer Average Volume': 'Day30PeerAverageVolume',
    'Peers: 30 Day Peer Average Volume 2x Standard Deviation':
        'Day30PeerAverageVolumeStandardDeviationX2',
    'Peers: 30 Day Peer Average Volume Standard Deviation':
        'Day30PeerAverageVolumeStandardDeviation',
    'Symbol: Extended Hours Change %': 'extendedChangePercent',
    'Peers: 30 Day Peer Average Price': 'Day30PeerAveragePrice',
    'Peers: 30 Day Peer Average Price Standard Deviation':
        'Day30PeerAveragePriceStandardDeviation',
    'Symbol: Shares Outstanding': 'sharesOutstanding',
    'Global: 1-Month Treasury': 'DGS1MO',
    'Global: 1-Year Treasury': 'DGS1',
    'Global: 10-Year Treasury': 'DGS10',
    'Global: 15-Year Mortgage Rate': 'MORTGAGE15US',
    'Global: 2-Year Treasury': 'DGS2',
    'Global: 20-Year Treasury': 'DGS20',
    'Global: 3-Month Treasury': 'DGS3MO',
    'Global: 30-Year Mortgage Rate': 'MORTGAGE30US',
    'Global: 30-Year Treasury': 'DGS30',
    'Global: 5-Year Mortgage Rate': 'MORTGAGE5US',
    'Global: 5-Year Treasury': 'DGS5',
    'Global: 6-Month Treasury': 'DGS6MO',
    'Global: Crude Brent Oil Price': 'DCOILBRENTEU',
    'Global: Crude Oil Price': 'DCOILWTICO',
    'Global: Sector': 'sector',
    'Global: Sector Change %': 'SectorChangePercent',
    'Global: Unemployment Rate': 'UNRATE',
    'Peers: 30 Day Peer Average Price 2x Standard Deviation':
        'Day30PeerAveragePriceStandardDeviationX2',
    'Symbol: 30 Day Average Price': 'Day30AveragePrice',
    'Symbol: 30 Day Average Price 2x Standard Deviation':
        'Day30AveragePriceStandardDeviationX2',
    'Symbol: 30 Day Average Price Standard Deviation':
        'Day30AveragePriceStandardDeviation',
    'Symbol: 30 Day Average Volume 2x Standard Deviation':
        'Day30AverageVolumeStandardDeviationX2',
    'Symbol: 30 Day Average Volume Standard Deviation':
        'Day30AverageVolumeStandardDeviation',
    'Symbol: CEO Salary': 'ceo_salary',
    'Symbol: Employees': 'employees',
    'Symbol: Exchange': 'exchange',
    'Symbol: Extended Price': 'extendedPrice',
    'Symbol: Float': 'float',
    'Symbol: Is Market Hours': 'isUSMarketOpen',
}

export const conditionsList: any = {
    metrics: [
        'Symbol: Change %',
        'Symbol: Latest Price',
        'Event: Dividend Next Day Ex',
        'Event: Dividend Today',
        'Event: Has News',
        'Symbol: Avg Volume',
        'Symbol: Change Amount',
        'Symbol: Dividend Rate',
        'Symbol: Dividend Yield',
        'Symbol: High',
        'Symbol: Low',
        'Symbol: Market Cap',
        'Symbol: PE Ratio',
        'Symbol: Peer Price Change %',
        'Symbol: Price Change % vs Peers',
        'Symbol: Price Change % vs Sector',
        'Symbol: Sector',
        'Symbol: YTD Change %',
        'Symbol: 10 Day Average Volume',
        'Symbol: 2 Year Change %',
        'Symbol: 200 Day Moving Average',
        'Symbol: 30 Day Average Volume',
        'Symbol: 30 Day Change %',
        'Symbol: 5 Day Change %',
        'Symbol: 5 Year Change %',
        'Symbol: 50 Day Moving Average',
        'Symbol: 52 Week Change %',
        'Symbol: 52 Week High',
        'Symbol: 52 Week Low',
        'Symbol: Beta',
        'Symbol: Current Debt',
        'Symbol: Debt to Equity',
        'Symbol: EBITDA',
        'Symbol: Enterprise Value',
        'Symbol: Enterprise Value to Revenue',
        'Symbol: Forward PE',
        'Symbol: PEG Ratio',
        'Symbol: Price to Book',
        'Symbol: Price to Sales',
        'Symbol: Profit Margin',
        'Symbol: Revenue',
        'Symbol: Revenue per employee',
        'Symbol: Revenue per share',
        'Symbol: Stock vs Sector Change %',
        'Symbol: Total Cash',
        'Symbol: Total Revenue',
        'Peers: 30 Day Peer Average Volume',
        'Peers: 30 Day Peer Average Volume 2x Standard Deviation',
        'Peers: 30 Day Peer Average Volume Standard Deviation',
        'Symbol: Extended Hours Change %',
        'Peers: 30 Day Peer Average Price',
        'Peers: 30 Day Peer Average Price Standard Deviation',
        'Symbol: Shares Outstanding',
        'Global: 1-Month Treasury',
        'Global: 1-Year Treasury',
        'Global: 10-Year Treasury',
        'Global: 15-Year Mortgage Rate',
        'Global: 2-Year Treasury',
        'Global: 20-Year Treasury',
        'Global: 3-Month Treasury',
        'Global: 30-Year Mortgage Rate',
        'Global: 30-Year Treasury',
        'Global: 5-Year Mortgage Rate',
        'Global: 5-Year Treasury',
        'Global: 6-Month Treasury',
        'Global: Crude Brent Oil Price',
        'Global: Crude Oil Price',
        'Global: Sector',
        'Global: Sector Change %',
        'Global: Unemployment Rate',
        'Peers: 30 Day Peer Average Price 2x Standard Deviation',
        'Symbol: 30 Day Average Price',
        'Symbol: 30 Day Average Price 2x Standard Deviation',
        'Symbol: 30 Day Average Price Standard Deviation',
        'Symbol: 30 Day Average Volume 2x Standard Deviation',
        'Symbol: 30 Day Average Volume Standard Deviation',
        'Symbol: Extended Price',
        'Symbol: Float',
        'Symbol: Is Market Hours',
    ],
    operators: {
        number: [
            'is above',
            'is above or equal to',
            'is below',
            'is below or equal to',
            'is',
            'is not',
        ],
        boolean: ['is'],
        string: ['is'],
        event: ['is'],
    },
    values: {
        boolean: ['True', 'False'],
        event: ['True', 'False'],
    },
}

export const operators: any = {
    '>': 'is above',
    '>=': 'is above or equal to',
    '<': 'is below',
    '<=': 'is below or equal to',
    '==': 'is',
    '!=': 'is not',
    true: 'True',
    false: 'False',
}

export const reverseOperators: any = {
    'is above': '>',
    'is above or equal to': '>=',
    'is below': '<',
    'is below or equal to': '<=',
    is: '==',
    'is not': '!=',
    True: 'true',
    False: 'false',
}
